<a href="https://colab.research.google.com/github/RecursionAndIteration/AIcourse/blob/main/Pandas_Library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
print(pd.__version__)
data={'Anna':25, 'Jan':42, 'Kasia':17}
s = pd.Series(data)
print(s)

2.2.2
Anna     25
Jan      42
Kasia    17
dtype: int64

In [ ]:
import numpy as np
s = pd.Series([13,25,3,6, np.nan], index=['Wojtek','Katarzyna','Kacper','Przemek','Nieznajomy'])
print(s)
print(s.size)
print(s.shape)
print(s.dtype)
print(s.index)
print(s.values)
print(s['Przemek'])
print(s.iloc[1])

Wojtek        13.0
Katarzyna     25.0
Kacper         3.0
Przemek        6.0
Nieznajomy     NaN
dtype: float64
5
(5,)
float64
Index(['Wojtek', 'Katarzyna', 'Kacper', 'Przemek', 'Nieznajomy'], dtype='object')
[13. 25.  3.  6. nan]
6.0
25.0

In [ ]:
data={
    "cena": [15,24,31],
    "ilosc": [50,50,1]
}
df = pd.DataFrame(data, index = ["dzien1","dzien2","dzien3"])
#df
print(df)
print(df.loc["dzien2"])
print("")
print(df.info())

        cena  ilosc
dzien1    15     50
dzien2    24     50
dzien3    31      1
cena     24
ilosc    50
Name: dzien2, dtype: int64

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, dzien1 to dzien3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cena    3 non-null      int64
 1   ilosc   3 non-null      int64
dtypes: int64(2)
memory usage: 180.0+ bytes
None

In [ ]:
df=pd.read_excel("Gigathon_Wyniki.xlsx")
#df

#print(df.head(5))
#print(df.tail(5))
df["Wynik procentowy"] = df["Punktacja"] / 120*100
df.dropna(inplace=True)
df.sort_values(by="Punktacja", ascending=False, inplace=True)
df["zakwalifikowany"] = df["Wynik procentowy"] >= 70

#df.groupby(["zakwalifikowany", "Wiek"])[["Punktacja", "Wynik procentowy"]].agg(["count","min","max","mean","median"])
df_zakwalifikowani = df[df["zakwalifikowany"] == True]
df_zakwalifikowani.drop("zakwalifikowany",axis=1, inplace=True)
#df_zakwalifikowani.drop(12, axis=0, inplace=True)
df_zakwalifikowani.to_excel("Zakwalifikowani.xlsx")
df_zakwalifikowani

/tmp/ipython-input-1772822497.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_zakwalifikowani.drop("zakwalifikowany",axis=1, inplace=True)

        Imię  Wiek  Punktacja  Wynik procentowy
12    Hubert    15      120.0        100.000000
6     Tomasz    16      112.0         93.333333
4       Anna    14      110.0         91.666667
7   Weronika    17      104.0         86.666667
22       Jan    17      102.0         85.000000
21   Urszula    14      102.0         85.000000
15     Filip    16      100.0         83.333333
16   Ewelina    17       98.0         81.666667
8    Nikodem    17       97.0         80.833333
11  Gabriela    16       92.0         76.666667
14    Oliwia    14       84.0         70.000000

In [12]:
import matplotlib.pyplot as plt

pokemo = pd.read_csv("Pokemon.csv")
#pokemo.head(10)

#pokemo["Type 1"].unique()

#pokemo_leg = pokemo[pokemo["Legendary"]==True]
#print(len(pokemo_leg))

#pokemo_nt2 = pokemo[pokemo["Type 2"].isnull()]
##pokemo_nt2
#print(len(pokemo_nt2))

#pokemo_tot = pokemo[pokemo["Total"]==pokemo["Total"].max()]
#pokemo_tot

#generation_counts = pokemo["Generation"].value_counts()
#plt.pie(generation_counts, labels=generation_counts.index, autopct='%1.1f%%')
#plt.show

#pokemof = pokemo[pokemo["Type 1"]=="Fire"]
#pokemof

#pokemoh = pokemo[pokemo["HP"]>100]
#pokemoh

#pokemo_legs = pokemo[(pokemo["Legendary"]==True) & (pokemo["Speed"] > 120)]
#pokemo_legs

#pokemo_ad = pokemo[(pokemo["Attack"]>100) & (pokemo["Defense"]<50)]
#pokemo_ad

#pokemo.groupby("Type 1")["HP"].mean()

#pokemo.groupby("Legendary")["Total"].mean()

#pokemo.groupby("Generation")["Speed"].mean()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True
453,408,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False
627,566,Archen,Rock,Flying,401,55,112,45,74,45,70,5,False